/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toadstool;

import org.junit.Test;
import static org.junit.Assert.*;

import java.sql.SQLException;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() throws SQLException {
        var context = new DefaultDatabaseContext("jdbc:postgresql://localhost:5432/tranquility");
        var connection = context.getConnection();

        var result = context.prepareStatement("select 1 as a, 2 as b, 3 as c where 'bar' = @foo")
                .withParameter("foo", "bar").build(connection);

        assertNotNull(result);
        var parameterMetadata = result.getParameterMetaData();
        assertNotNull(parameterMetadata);
        assertEquals(1, parameterMetadata.getParameterCount());
    }

    @Test
    public void testToList() throws SQLException {
        var context = new DefaultDatabaseContext("jdbc:postgresql://localhost:5432/tranquility");

        var results = context.prepareStatement("select 1 as a, 2 as b, 3 as c where 'bar' = @foo")
                .withParameter("foo", "bar").ToListOf(Foo.class);

        assertNotNull(results);
        assertEquals(1, results.size());
        var first = results.get(0);
        assertNotNull(first);
        assertEquals(1, first.a);
    }
}
