/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toadstool;

import org.junit.Test;
import static org.junit.Assert.*;

import java.sql.SQLException;
import java.util.List;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() throws SQLException {
        var context = new SimpleDatabaseContext("jdbc:postgresql://localhost:5432/tranquility");
        var connection = context.getConnection();

        // @formatter:off
        var result = context
            .prepareStatement("select 1 as a, 2 as b, 3 as c where 'bar' = @foo")
            .withParameter("foo", "bar")
            .build(connection);
        // @formatter:on        

        assertNotNull(result);
        var parameterMetadata = result.getParameterMetaData();
        assertNotNull(parameterMetadata);
        assertEquals(1, parameterMetadata.getParameterCount());
    }

    @Test
    public void testToList() throws SQLException {
        var context = new SimpleDatabaseContext("jdbc:postgresql://localhost:5432/tranquility");

        // @formatter:off
        var results = context
            .prepareStatement("select 1 as a, 2 as b, 3 as c, 4 as d where 'bar' = @foo")
            .withParameter("foo", "bar")
            .toListOf(Foo.class);
        // @formatter:on

        assertNotNull(results);
        assertEquals(1, results.size());
        var first = results.get(0);
        assertNotNull(first);
        assertEquals(1, first.getA());
        assertEquals(2, first.getB());
        assertEquals(3, first.getC());
    }

    @Test
    public void testFirst() throws SQLException {
        var context = new SimpleDatabaseContext("jdbc:postgresql://localhost:5432/tranquility");

        // @formatter:off
        var result = context
            .prepareStatement("select 1 as a, 2 as b, 3 as c, 4 as d where 'bar' = @foo")
            .withParameter("foo", "bar")
            .first(Foo.class);
        // @formatter:on

        assertNotNull(result);
        assertTrue("Optional must not be empty", result.isPresent());
        var first = result.get();
        assertNotNull(first);
        assertEquals(1, first.getA());
        assertEquals(2, first.getB());
        assertEquals(3, first.getC());
    }

    @Test
    public void testMultipleParameterUse() throws SQLException {
        var context = new SimpleDatabaseContext("jdbc:postgresql://localhost:5432/tranquility");

        // @formatter:off
        var result = context
            .prepareStatement("select 1 as a, 2 as b, 3 as c, 4 as d where 'bar' = @foo or 'bat' = @foo or 'baz' = @foo or 'bag' = '@banana'")
            .withParameter("foo", "bar")
            .first(Foo.class);
        // @formatter:on

        assertNotNull(result);
        assertTrue("Optional must not be empty", result.isPresent());
        var first = result.get();
        assertNotNull(first);
        assertEquals(1, first.getA());
        assertEquals(2, first.getB());
        assertEquals(3, first.getC());
    }
}
